
project_id = "fofatokkoxbnbhdgtxic"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://fofatokkoxbnbhdgtxic.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = false

[auth.email]
enable_signup = true

[functions.html-to-pdf]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-scheduled-notifications]
verify_jwt = false

[functions.docusign-create-envelope]
verify_jwt = false

[functions.create-docusign-envelope]
verify_jwt = false

[functions.autentique-webhook]
verify_jwt = false
