// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fofatokkoxbnbhdgtxic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvZmF0b2trb3hibmJoZGd0eGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTEyNDcsImV4cCI6MjA2MzU4NzI0N30.VN7vssHRBWN6IhupYGauLyBu-EZWv1f4oln8-xBtwIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);